### ISSUE TITLE
how to understand FLAG  in the SAM format file.

### ISSUE THREAD

**Issue by WinterLi1993** [lh3/samtools#23]
您好，老师，
      我知道您是中国人，所以这里我用中文来问您问题啦。
      请教一个问题啊，SAM 文件中的FLAG 具体是什么含义？ 我看了解释，但是还是不太清楚。
     例如，如果FLAG 是 163， 意味什么呢？？您能给详细的解释一下吗？？

谢谢！！！

**Comment by lh3** [comment]
Use [this](https://broadinstitute.github.io/picard/explain-flags.html). Also, please write in English. You will have a much higher chance to find the help.

**Comment by WinterLi1993** [comment]
Professor Li,
       thank you for your help !  
       How to know the strand orientation for each alignment in a bam ?
       I wanna judge  it's whether + strand or  - strand when I read every alignment in My perl Program.
